lsi: false
safe: true

source: .

title: Hack for LA
email: hello@hackforla.org
description: Can you design, write, or code? Are you an activist with an idea? You can help Los Angeles live up to its potential at Hack for LA. Everyone is welcome!

baseurl: ""
url: https://www.hackforla.org


collections:
  press:
  projects:
    output: true
  credits:
  toolkitResources:
  sponsors:
  testimonials:
  guide-pages:
    output: true

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "guide-pages"
    values:
      layout: "guide-pages"
