---
title: Security
title-link: https://thenounproject.com/search/?q=security&i=2995532
content-type: image
used-in: Getting Started
artist: Graphik Designz
provider: Noun Project
provider-link: 'https://thenounproject.com/'
image-url: /assets/images/getting-started/adopt-1.png
alt: 'Security Icon'
---
