name: Lint SCSS

on:
  pull_request:
    branches: [gh-pages]
  push:
    branches: [gh-pages]

jobs:
  build:
    name: Lint SCSS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint SCSS
        uses: github/super-linter@v5.0.0
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


          LINTER_RULES_PATH: /
          CSS_FILE_NAME: .stylelintrc.json
          VALIDATE_CSS: true
