name: Add Pull Request Instructions
on:
  pull_request:
    types: [opened]
    branches:
      - 'gh-pages'
      - 'feature-homepage-launch'

jobs:
  Add-Pull-Request-Instructions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Create the message to post
      - name: Create Instruction
        uses: actions/github-script@v7
        id: instruction
        with:
          script: |
            const script = require('./github-actions/pr-instructions/create-instruction.js')
            return script({g: github, c: context}).then((instruction) => {
              return JSON.stringify({ instruction: instruction, issueNum: context.payload.number })
            })
      
      # Create an artifact with the message
      - name: Create Artifacts
        run: |
          mkdir -p addingPrInstructions/artifact
          echo ${{ steps.instruction.outputs.result }} > addingPrInstructions/artifact/artifact.txt
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: adding-pr-instructions-artifact
          path: addingPrInstructions/artifact/
  
  Check-Team-Membership:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          repo-token: ${{ secrets.HACKFORLA_BOT_PA_TOKEN }}
          script: |
            const prAuthor = context.payload.sender.login;
            const prNumber = context.payload.number;
            try {
              const getMembershipStatus = await github.rest.teams.getMembershipForUserInOrg({
              org: 'hackforla',
              team_slug: 'website-write',
              username: prAuthor
              });
              console.log('Successfully verified!')
            } catch (verificationError) {
              if (verificationError.status==404) {
                await github.request('PATCH /repos/{owner}/{repo}/pulls/{pull_number}', {
                  owner : 'hackforla',
                  repo : 'website',
                  pull_number : prNumber,
                  state : 'closed'
                });
                await github.request('POST /repos/{owner}/{repo}/issues/{issue_number}/comments', {
                  owner : 'hackforla',
                  repo : 'website',
                  issue_number : prNumber,
                  body : 'You must be a member of the HFLA website team in order to create pull requests. Please see our page on how to join us as a member at HFLA: https://www.hackforla.org/getting-started.  If you have been though onboarding, and feel this message in error, please message us in the #hfla-site team slack channel with the link to this PR.'
                });
              }
              }