name: Pull Request Verification
on:
  pull_request_target:
    types: [opened]
    branches:
      - 'gh-pages'

jobs:
  Check-Team-Membership:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.HACKFORLA_ADMIN_TOKEN }}
          script: |
            const prAuthor = "test";
            const prNumber = 100;
            try {
              const getMembershipStatus = await github.rest.teams.getMembershipForUserInOrg({
              org: 'hackforla',
              team_slug: 'website-write',
              username: prAuthor
              });
              if(getMembershipStatus.data) console.log(getMembershipStatus.data);
              //console.log('Successfully verified!')
            } catch (verificationError) {
              if (verificationError.status==404) {
                await github.request('PATCH /repos/{owner}/{repo}/pulls/{pull_number}', {
                  owner : 'moazDev1',
                  repo : 'test',
                  pull_number : prNumber,
                  state : 'closed'
                });
                await github.request('POST /repos/{owner}/{repo}/issues/{issue_number}/comments', {
                  owner : 'moazDev1',
                  repo : 'test',
                  issue_number : prNumber,
                  body : 'You must be a member of the HFLA website team in order to create pull requests. Please see our page on how to join us as a member at HFLA: https://www.hackforla.org/getting-started.  If you have been though onboarding, and feel this message in error, please message us in the #hfla-site team slack channel with the link to this PR.'
                });
              }
              }
  
