name: Update wins data

# Run this action every day at 4am Pacific (12 am UTC)
on:
  schedule:
    - cron: '0 12 * * *'

jobs:
  vrms_data:
    runs-on: ubuntu-latest
    
    if: github.repository == 'hackforla/website'

    steps:
    - uses: actions/checkout@v2

    - name: Save wins-data.json
      run: curl -o _data/external/wins-data.json https://sheets.googleapis.com/v4/spreadsheets/1tj6eQlVLFgmskoXouVt87POxYVwR1yWT2vOSQEPyDtg/values/Responses?key=${{ secrets.WINS_API_KEY }}

    - uses: stefanzweifel/git-auto-commit-action@v3.0.0
      with:
        # Optional glob pattern of files which should be added to the commit
        file_pattern: _data/external/wins-data.json

        commit_message: Update wins data

        # Optional commit user and author settings
        commit_author: GitHub Actions Bot <hackforla-bot@hackforla.org>

